# Setup
title:  "@AlexisTM's project list"
description: "Simple blog about AlexisTM's work"
tagline:    'AlexisTM Alexis Paques'
logo :      '/assets/images/logo.png'
logowhite : '/assets/images/logo-white.png'
logoblack : '/assets/images/logo-black.png'
url:        'http://alexistm.github.io/'
baseurl:    ''
favicon:    '/assets/images/favicon.ico'

# Author Details
author:         'Alexis Paques'
pseudo:         'AlexisTM'
github:         'https://github.com/AlexisTM'
linkedin:       'https://be.linkedin.com/in/alexispaques'
stackoverflow:  'http://stackoverflow.com/users/3540247/alexis-paquesace'

# Google Analytics
gahandler: ''

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: ''

# Blog Configurations
paginate: 10 # Posts per page on the blog index# Permalinks
permalink:      /blog/:title/
paginate_path: '/blog/page:num'
destination:   ./_site

# Custom vars
version:          '1.0'

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Kalman
  url: /kalman/
- text: Neural
  url: /neuralcolor/


# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

markdown_ext:  markdown,mkdown,mkdn,mkd,md 

highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-paginate